### ISSUE TITLE
Correctness of Skein implementation

### ISSUE THREAD

**Issue by verement** [vincenthz/hs-cryptohash#34]
Has the Skein implementation been verified?

The reason I ask is I can’t seem to reproduce the test vectors from the [Skein paper](http://www.skein-hash.info/sites/default/files/skein1.1.pdf):

    C.1 Skein-256-256

    Message data:
         FF

    Result:
         A4 7B E7 1A 18 5B A0 AF 82 0B 3C E8 45 A3 D3 5A
         80 EC 64 F9 6A 0D 6A 36 E3 F5 36 36 24 D8 A0 91

In `ghci`:

    Prelude Crypto.Hash Data.ByteString> hash $ pack [0xFF] :: Digest Skein256_256
    0b98dcd198ea0e50a7a244c444e25c23da30c10fc9a1f270a6637f1f34e67ed2

Am I overlooking something?

Thanks.

**Comment by vincenthz** [comment]
skein is version 1.3 now; all the test vectors are differents now

**Comment by verement** [comment]
Ah, thank you!
