### ISSUE TITLE
Document move from `cryptohash` to `cryptonite`

### ISSUE THREAD

**Issue by gasi** [vincenthz/hs-cryptohash#39]
First of all, thanks for providing this library. I am a Haskell beginner and first stumbled upon `cryptohash` and only later found your blog post about the consolidation to `cryptonite`. Could you please add a link to your blog post in the `README.md` as well as the Hackage page so newcomers know about `cryptonite`? Thanks.

_P.S. Let me know if you’d prefer me to open a PR._

**Comment by angerman** [comment]
I just ran into the same issue. When browsing packages, finding `cryptohash` and `cryptonite`, an no deprecation note (as with some other package), is really confusing.

**Comment by rvion** [comment]
@vincenthz I also wish you could 
deprecate [cryptohash](https://www.stackage.org/nightly-2016-04-19/package/cryptohash-0.11.9)  
![image](https://cloud.githubusercontent.com/assets/2150990/14645758/3da3bb1e-0657-11e6-9104-4ed83187c614.png)

as you did for [cprng-aes](https://www.stackage.org/nightly-2016-04-19/package/cprng-aes-0.6.1) for instance 

![image](https://cloud.githubusercontent.com/assets/2150990/14645773/49ba3cd4-0657-11e6-9648-8e1e02b18b99.png)

As of now, it's not direclty clear that cryptohash should be avoided

**Comment by vincenthz** [comment]
It's now deprecated almost everywhere (cabal header, README, ..), apart from officially from hackage. it's still fully functional and still willing to maintain it, as they are many users of it, which is the only reason why I don't flip the switch.

**Comment by angerman** [comment]
I've run into minor issues with packages using `cryptohash`, when I was using `cryptonite`, ending up with incompatible, yet identically named, data structures. Package imports solve this to a certain degree.

Isn't cryptonite a superset and almost a stand-in replacement for crytpohash? Or am I missing something?
