### ISSUE TITLE
Consider using hashabler to support hashing arbitrary types

### ISSUE THREAD

**Issue by jberryman** [vincenthz/hs-cryptohash#40]
Would you be interested in merging changes that permitted hashing of arbitrary [`Hashable`](http://hackage.haskell.org/package/hashabler-1.2.1/docs/Data-Hashabler.html#t:Hashable) types from my `hashabler` package? The resulting hash functions would probably look like:

    hash :: Hashable a=> a -> ByteString

where `a` may also be bytestring. This would allow hashing of arbitrary haskell values in a performant way (without needing to marshal to a bytestring first), and cross-platform compatible way, etc.

I'm not sure when I'd be able to get to this, but I wanted to float the idea first.

**Comment by vincenthz** [comment]
Nothing is expected to change in `cryptohash`, as it is a maintenance only and all further development are in `cryptonite`.

One thing is that Hashabler seems terribly misnamed, it's a fold-over-variable-length-atoms class (which is an interesting idea). It also reimplement much part of `memory` which got hashes and a more efficient fold-over-memory-chunks class (ByteArrayAccess). I've also become completely allergic to dependencies in Haskell as they add a unpredictable cost to development on things.

**Comment by jberryman** [comment]
Thanks for the pointer to the `memory` package.

**Comment by jberryman** [comment]
...although looking at the dates it looks like it's `memory` that reimplemented much of hashabler :-P

**Comment by vincenthz** [comment]
looks can be deceiving; The repository doesn't represent the actual history, most of memory lived in cryptonite before hashabler (beginning 2015), and before that in individual packages like byteable (2013) and securemem (2013), siphash (2012) and some other apps.
